global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
  
    static_configs:
      - targets: ['127.0.0.1:9100']
  
  - job_name: 'spring-boot-app'

    metrics_path: '/metrics'

    static_configs:
      - targets: ['127.0.0.1:8080']