name: Docker Image CI

on:
  push:
    branches: [ "main", "grafana" ]
    paths-ignore:
      - 'README.md'
      - 'www-data/**'
  pull_request:
    branches: [ "main", "grafana" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    -
        name: Login to OCIR
        uses: docker/login-action@v3
        with:
          registry: fra.ocir.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.AUTH_TOKEN }}
          
    - name: Build and Push the Sidecar image to OCIR
      run: |
        cd sidecar
        docker build . -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/prometheus-sidecar:1.0.0
        docker push -q fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/prometheus-sidecar:1.0.0
    -
          name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven
    - name: Build with Maven
      run: |
        cd PrometheusJavaDemo
        mvn clean package
        docker build . -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/prometheusjavademo:1.0.0
        docker push -q fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/prometheusjavademo:1.0.0
